#ifndef __UTILS_SHARED_CODES_H__
#define __UTILS_SHARED_CODES_H__

#define TDC_SUCCESS 100
#define TDC_FAILURE 101

#define TDCE_RESERVE_SPACE 400
#define TDCE_NULL_POINTER 401
#define TDCE_MAP_SUBMIT 402
#define TDCE_UNKNOWN_TYPE 403
#define TDCE_UNDEFINED_INDEX 404
#define TDCE_WRITE_CWD 405
#define TDCE_SCRATCH_SPACE_ALLOCATION 406

#endif