EXECUTABLE=bin

gen:
	go generate ./...

build: gen
	go build -o ./$(EXECUTABLE)/ ./cmd/...

fmt: ## Run go fmt against code.
	go fmt ./...

vet: ## Run go vet against code.
	go vet ./...

lint: fmt vet
	revive -formatter stylish -config .revive.toml ./pkg/...
	staticcheck ./...

