// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package network_bind

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bindEventData struct{ Args [3]uint64 }

// loadBind returns the embedded CollectionSpec for bind.
func loadBind() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BindBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bind: %w", err)
	}

	return spec, err
}

// loadBindObjects loads bind and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bindObjects
//	*bindPrograms
//	*bindMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBindObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBind()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bindSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bindSpecs struct {
	bindProgramSpecs
	bindMapSpecs
}

// bindSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bindProgramSpecs struct {
	KprobeBind *ebpf.ProgramSpec `ebpf:"kprobe_bind"`
}

// bindMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bindMapSpecs struct {
	Event *ebpf.MapSpec `ebpf:"event"`
}

// bindObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBindObjects or ebpf.CollectionSpec.LoadAndAssign.
type bindObjects struct {
	bindPrograms
	bindMaps
}

func (o *bindObjects) Close() error {
	return _BindClose(
		&o.bindPrograms,
		&o.bindMaps,
	)
}

// bindMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBindObjects or ebpf.CollectionSpec.LoadAndAssign.
type bindMaps struct {
	Event *ebpf.Map `ebpf:"event"`
}

func (m *bindMaps) Close() error {
	return _BindClose(
		m.Event,
	)
}

// bindPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBindObjects or ebpf.CollectionSpec.LoadAndAssign.
type bindPrograms struct {
	KprobeBind *ebpf.Program `ebpf:"kprobe_bind"`
}

func (p *bindPrograms) Close() error {
	return _BindClose(
		p.KprobeBind,
	)
}

func _BindClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bind_bpfel_x86.o
var _BindBytes []byte
