// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64
// +build 386 amd64

package file_open

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type openEventData struct {
	Pid      uint32
	Tgid     uint32
	Uid      uint32
	Gid      uint32
	Filename [256]uint8
	Flags    int32
}

// loadOpen returns the embedded CollectionSpec for open.
func loadOpen() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OpenBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load open: %w", err)
	}

	return spec, err
}

// loadOpenObjects loads open and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*openObjects
//	*openPrograms
//	*openMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOpenObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOpen()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// openSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openSpecs struct {
	openProgramSpecs
	openMapSpecs
}

// openSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openProgramSpecs struct {
	KprobeOpen *ebpf.ProgramSpec `ebpf:"kprobe_open"`
}

// openMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type openMapSpecs struct {
	Event *ebpf.MapSpec `ebpf:"event"`
}

// openObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openObjects struct {
	openPrograms
	openMaps
}

func (o *openObjects) Close() error {
	return _OpenClose(
		&o.openPrograms,
		&o.openMaps,
	)
}

// openMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openMaps struct {
	Event *ebpf.Map `ebpf:"event"`
}

func (m *openMaps) Close() error {
	return _OpenClose(
		m.Event,
	)
}

// openPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOpenObjects or ebpf.CollectionSpec.LoadAndAssign.
type openPrograms struct {
	KprobeOpen *ebpf.Program `ebpf:"kprobe_open"`
}

func (p *openPrograms) Close() error {
	return _OpenClose(
		p.KprobeOpen,
	)
}

func _OpenClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed open_bpfel_x86.o
var _OpenBytes []byte
